name: psychelink_study
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2   
  flutter_native_splash: ^2.3.2

flutter_native_splash:
  color: "#1B1A1F"  
  color_dark: "#1B1A1F"
  android: true
  ios: true  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  #添加资源目录
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/usefulBanner/
    - assets/singleImages/
    - assets/words.json
  fonts:
    - family: AMSTERDAM-SERIF
      fonts:
        - asset: assets/fonts/AMSTERDAM-SERIF.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic      